# Generated by Django 5.0.3 on 2026-04-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('luxury', 'Luxury'), ('pickup', 'Pickup')], max_length=20)),
                ('price_daily', models.PositiveIntegerField()),
                ('price_weekly', models.PositiveIntegerField()),
                ('price_monthly', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('image_url', models.URLField(blank=True, help_text='External image URL if not uploading', null=True)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], max_length=20)),
                ('seats', models.PositiveSmallIntegerField()),
                ('luggage', models.PositiveSmallIntegerField()),
                ('ac', models.BooleanField(default=True)),
                ('engine', models.CharField(blank=True, max_length=20)),
                ('mileage', models.CharField(blank=True, max_length=30)),
                ('features', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('available', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
