# Generated by Django 5.0.3 on 2026-04-21 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'About Page'), ('terms', 'Terms of Service'), ('privacy', 'Privacy Policy')], max_length=20, unique=True)),
                ('content', models.TextField(help_text='HTML content for the page')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Content',
                'verbose_name_plural': 'Page Contents',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_url', models.CharField(blank=True, help_text='Path or URL to payment icon', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_primary', models.CharField(default='+880 1849448321', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, default='+880 1849448321', max_length=20)),
                ('email_primary', models.EmailField(default='info@sslrentacarbd.com', max_length=254)),
                ('email_secondary', models.EmailField(blank=True, default='support@sslrentacarbd.com', max_length=254)),
                ('address', models.TextField(default='House 123, Road 45, Dhanmondi, Dhaka - 1209, Bangladesh')),
                ('business_hours', models.TextField(default='Sunday - Wednesday: 9:00 AM - 9:00 PM\nThursday - Saturday: 9:00 AM - 10:00 PM')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/sslrentacarbd')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/sslrentacarbd')),
                ('twitter_url', models.URLField(blank=True)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('hero_title_line1', models.CharField(default='Your Journey Begins', max_length=100)),
                ('hero_title_line2', models.CharField(default='With Perfect Ride', max_length=100)),
                ('hero_subtitle', models.CharField(default='Experience luxury, comfort, and reliability with our premium fleet. Explore Bangladesh like never before.', max_length=200)),
                ('hero_badge_text', models.CharField(default='Premium Car Rental in Bangladesh', max_length=100)),
                ('copyright_year', models.CharField(default='2026', max_length=4)),
                ('copyright_text', models.CharField(default='SSL Rent a Car BD. All rights reserved.', max_length=200)),
                ('site_description', models.TextField(blank=True, default='Premium car rental services across Bangladesh. Book your perfect ride with SSL Rent a Car BD.')),
                ('site_keywords', models.CharField(blank=True, default='car rental Bangladesh, rent a car Dhaka, luxury car hire, premium car rental', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=20)),
                ('icon_class', models.CharField(default='bi bi-car-front', help_text='Bootstrap Icon class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('pickup_date', models.DateField()),
                ('dropoff_date', models.DateField()),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('rental_days', models.PositiveIntegerField()),
                ('daily_rate', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('discount', models.FloatField(default=0)),
                ('total', models.PositiveIntegerField()),
                ('booking_reference', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pages.car')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
