# Generated by Django 5.0.3 on 2026-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contactinquiry_pagecontent_paymentmethod_sitesetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='nid_passport',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='NID/Passport'),
        ),
    ]
