# Generated by Django 5.0.3 on 2026-04-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_booking_nid_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
