# Generated by Django 5.0.3 on 2026-04-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_booking_email_verified_booking_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, help_text='Upload payment method icon image', null=True, upload_to='payment_methods/'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon_url',
            field=models.CharField(blank=True, help_text='Path or URL to payment icon (fallback if no upload)', max_length=200),
        ),
    ]
